### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by nova-techies** [ZedPea/rule34-paheal-downloader#1]
I'm trying to install this but I'm getting this error currenlty.

> Invalid package ID: "array-0.5.1.1 base-4.9.0.0 binary-0.8.3.0 bytestring-0.10.8.1"

I've tried installing them manually but that doesn't seem to do it either.  I'm running this on Ubuntu 16.04.2 LTS.

**Comment by ZedPea** [comment]
Sorry for the slow response, github doesn't seem to email you on issue unless you watch your projects, I've fixed that now.

It looks like you might need a newer version of stack, try running 

stack upgrade --git

And then re-running the stack instructions. 

It looks like GHC 8 changed the way package info is outputted, so if you use that you need a fixed version of stack.

Let me know if that fixes it and i'll add it to the readme or see if I can check that GHC version from the stack setup.

**Comment by ZedPea** [comment]
I managed to replicate the issue, and have updated the build instructions. Let me know if it works for you, and I'll close this.

**Comment by nova-techies** [comment]
Give me a few days.  I'm not at home right now.  I'll be back on 06-08-17.

**Comment by ZedPea** [comment]
@nova-techies 

A version of stack that can parse GHC 8's output is no longer required due to an issue with hsqml building on windows with GHC 8, so I'm going to assume this has solved itself.

 Feel free to re-open if it still doesn't work with the latest version of the code.
